const K = [
  // ═══ SALUDOS & PRESENTACIÓN ═══
  {k:['hola','bueno','día','saludo','hey','que','tal','como','estas'], a:'¡Hola! Soy X0GPT, tu asistente IA. Estoy aquí para ayudarte con lo que necesites. ¿Qué te gustaría saber o preguntar?'},
  {k:['gracias','mucho','agradezco','graci','thank','agradecido'], a:'¡De nada! Un placer ayudarte. Si necesitas algo más, aquí estaré.'},
  {k:['adiós','chao','hasta','luego','nos','vemos','bye','hasta pronto','cuídate','pronto'], a:'¡Hasta luego! Cuídate mucho. Si necesitas ayuda en otro momento, no dudes en volver.'},
  {k:['quien','eres','x0gpt','que','eres','creador','hiciste','creaste'], a:'Soy X0GPT, un asistente de inteligencia artificial creado por Jaime Muñoz. Funciono completamente en tu navegador, sin internet, sin descargas y sin instalar nada. Todo el procesamiento es local, privado y gratuito. Estoy aquí para responder preguntas, dar consejos, explicar conceptos y ayudarte en lo que necesites.'},
  {k:['que','puede','hacer','funcion','capaz','ayudar','servicio','sirve','tareas','util'], a:'Puedo hacer muchas cosas: responder preguntas sobre ciencia, historia, geografía, tecnología, salud y más. Darte consejos de supervivencia, primeros auxilios, cocina y finanzas. Explicarte conceptos de programación, IA y matemáticas. Hablar de filosofía, arte y cultura. Y todo esto 100% offline y privado.'},
  {k:['como','funcion','trabajas','mecanismo','motor','procesas','funcionas'], a:'Funciono con un motor de procesamiento de lenguaje natural que analiza tus palabras, identifica la intención y busca la mejor respuesta en mi base de conocimiento. Combino varias técnicas como stemming, detección de bigramas, y coincidencia semántica para entender tus preguntas. Todo se ejecuta localmente en tu navegador, sin enviar datos a ningún servidor.'},
  {k:['bien','estoy','bien y tu','todo bien','genial','excelente','contento','feliz'], a:'¡Me alegra mucho que estés bien! Espero poder ayudarte con lo que necesites. ¿Qué te gusta saber hoy?'},

  // ═══ CIENCIA ═══
  {k:['tierra','mundo','planeta','sistema','solar','órbita','globo','terráqueo'], a:'La Tierra es el tercer planeta del sistema solar, a unos 150 millones de km del Sol. Tiene un diámetro de 12.742 km. El 71% de su superficie está cubierta de agua. Su atmósfera está compuesta principalmente de nitrógeno (78%) y oxígeno (21%). Tarda 365.25 días en orbitar el Sol y 24 horas en rotar sobre su eje. Es el único planeta conocido que alberga vida.'},
  {k:['sol','estrella','energía','solar','calor','luz','fusión','nuclear'], a:'El Sol es una estrella enana amarilla (tipo G2V) compuesta por ~73% hidrógeno y ~25% helio. Genera energía mediante fusión nuclear en su núcleo a 15 millones de °C. Cada segundo convierte 600 millones de toneladas de hidrógeno en helio. La luz solar tarda ~8 minutos en llegar a la Tierra. Tiene unos 4,600 millones de años y le quedan ~5,000 millones de años de vida antes de convertirse en gigante roja.'},
  {k:['luna','satélite','natural','fase','lunar','eclipse','apolo','pisada'], a:'La Luna es el único satélite natural de la Tierra. Tiene un diámetro de 3.474 km y está a 384.400 km de la Tierra. Sus fases son: nueva, creciente, llena y menguante. Tarda ~27.3 días en orbitar la Tierra. La primera vez que el hombre pisó la Luna fue el 20 de julio de 1969 (misión Apolo 11, Neil Armstrong). La Luna no tiene atmósfera ni agua líquida.'},
  {k:['agujero','negro','agrave','singularidad','horizonte','suceso','gravedad','colaps'], a:'Un agujero negro es una región del espacio con una gravedad tan intensa que nada puede escapar, ni siquiera la luz. Se forma cuando una estrella masiva colapsa sobre sí misma. El límite alrededor se llama horizonte de sucesos. El primer agujero negro fotografiado fue M87* en 2019. Sagitario A*, en el centro de nuestra galaxia, tiene 4 millones de masas solares. Son invisibles, solo detectables por su efecto gravitacional.'},
  {k:['gravedad','ley','newton','einstein','relatividad','atracción','masa','peso'], a:'La gravedad es una fuerza fundamental que atrae objetos con masa. Newton la describió como una fuerza universal (Ley de Gravitación Universal: F = G·m₁·m₂/r²). Einstein la revolucionó con la Relatividad General (1915), describiéndola como la curvatura del espacio-tiempo causada por la masa y la energía. La aceleración gravitacional en la Tierra es de 9.8 m/s². En la Luna es 1.6 m/s², en Marte 3.7 m/s².'},
  {k:['física','cuántica','mecánica','cuántico','partícula','átomo','subatómico','schrödinger','heisenberg','planck'], a:'La mecánica cuántica describe la naturaleza a escala atómica y subatómica. Conceptos clave: 1) Dualidad onda-partícula (la luz se comporta como onda y partícula). 2) Principio de incertidumbre de Heisenberg (no se puede conocer posición y momento exactos a la vez). 3) Superposición cuántica (una partícula existe en múltiples estados hasta que se mide). 4) Entrelazamiento cuántico (partículas conectadas instantáneamente a distancia).'},
  {k:['adn','gen','genética','cromosoma','herencia','mutación','doble','hélice','genoma'], a:'El ADN (ácido desoxirribonucleico) contiene la información genética en forma de doble hélice, descubierta por Watson y Crick en 1953. Los genes son segmentos de ADN que codifican proteínas. Los humanos tenemos ~20.000-25.000 genes en 23 pares de cromosomas. El genoma humano se secuenció completamente en 2003 (Proyecto Genoma Humano). Las mutaciones son cambios en el ADN que pueden ser neutros, beneficiosos o dañinos.'},
  {k:['evolución','darwin','especie','selección','natural','adaptación','supervivencia','origen'], a:'La teoría de la evolución por selección natural fue propuesta por Charles Darwin en "El origen de las especies" (1859). Postula que los organismos con características ventajosas para su entorno tienen más probabilidades de sobrevivir y reproducirse, transmitiendo esas características a su descendencia. Ejemplos: el camuflaje de los insectos, la resistencia bacteriana a antibióticos, el cuello largo de las jirafas. La evolución está respaldada por fósiles, genética y observación directa.'},
  {k:['dinosaurio','extinción','fósil','prehistórico','mesozoico','jurásico','cretácico','tiranosaurio','triceratops','velociraptor'], a:'Los dinosaurios dominaron la Tierra durante la era Mesozoica (252-66 millones de años atrás). Se extinguieron hace ~66 millones de años por el impacto de un asteroide en Chicxulub (Yucatán, México), que provocó cambios climáticos catastróficos. Hoy sobreviven como aves (descendientes de terópodos). El dinosaurio más grande conocido es el Argentinosaurus (~35m, ~70 toneladas). El T-Rex medía ~12m y pesaba ~8 toneladas.'},
  {k:['célula','orgánulo','núcleo','mitocondria','membrana','citoplasma','ribosoma','eucariota','procariota'], a:'La célula es la unidad básica de la vida. Tipos: procariotas (sin núcleo, como bacterias) y eucariotas (con núcleo, como plantas y animales). Orgánulos principales: núcleo (contiene ADN), mitocondrias (generan energía), ribosomas (sintetizan proteínas), retículo endoplasmático (síntesis de lípidos y proteínas), aparato de Golgi (empaqueta moléculas), lisosomas (digestión celular). El cuerpo humano tiene ~37 billones de células.'},
  {k:['océano','mar','agua','profundidad','ola','corriente','biodiversidad','marino','coral','ballena','delfín','pez','marino'], a:'Los océanos cubren el 71% de la superficie terrestre y contienen el 97% del agua del planeta. El océano Pacífico es el más grande (165 millones km²). El punto más profundo es la Fosa de las Marianas (11.034 m). Los océanos producen el 50% del oxígeno que respiramos (fitoplancton). La Gran Barrera de Coral (Australia) es el mayor arrecife del mundo. Lamentablemente, están amenazados por plásticos, sobrepesca y acidificación.'},
  {k:['atmósfera','capa','ozono','troposfera','estratosfera','ionosfera','oxígeno','nitrógeno','aire'], a:'La atmósfera terrestre es una capa de gases que rodea el planeta. Se divide en: troposfera (0-12 km, donde ocurre el clima), estratosfera (12-50 km, contiene la capa de ozono), mesosfera (50-80 km), termosfera (80-700 km) y exosfera (700+ km). Compuesta por 78% nitrógeno, 21% oxígeno y 1% otros gases (argón, CO₂, vapor de agua). La capa de ozono nos protege de la radiación UV.'},
  {k:['cambio','climático','calentamiento','global','emisio','co2','carbono','efecto','invernadero','ecología','ambiente','sostenible','huella'], a:'El cambio climático es el aumento de la temperatura global por emisiones de gases de efecto invernadero. Causas: quema de combustibles fósiles, deforestación, agricultura intensiva. Efectos: derretimiento de glaciares, aumento del nivel del mar, fenómenos extremos (huracanes, sequías), pérdida de biodiversidad. Cómo ayudar: reduce tu huella de carbono (usa transporte público, ahorra energía, recicla, consume menos carne).'},
  {k:['energía','renovable','solar','eólica','hidroeléctrica','biomasa','geotérmica','limpia','verde','sustentable'], a:'Energías renovables: 1) Solar: paneles fotovoltaicos convierten luz en electricidad. 2) Eólica: aerogeneradores usan el viento. 3) Hidroeléctrica: aprovecha el agua en movimiento. 4) Geotérmica: calor interno de la Tierra. 5) Biomasa: materia orgánica como combustible. Ventajas: limpias, inagotables, reducen dependencia de combustibles fósiles. Desventajas: intermitencia (sol/viento no constantes), alto costo inicial, impacto ambiental local.'},
  {k:['fotosíntesis','clorofila','planta','cloroplasto','luz','solar','oxígeno','dióxido','carbono','glucosa'], a:'La fotosíntesis es el proceso por el cual las plantas convierten luz solar en energía química. Ocurre en los cloroplastos (contienen clorofila, el pigmento verde). Ecuación: 6CO₂ + 6H₂O + luz → C₆H₁₂O₆ + 6O₂. Es decir, las plantas toman dióxido de carbono y agua, y con energía solar producen glucosa (su alimento) y liberan oxígeno. Es esencial para la vida porque produce el oxígeno que respiramos y es la base de la cadena alimenticia.'},
  {k:['volcán','erupción','magma','lava','ceniza','cráter','placa','tectónica','dormido','activo'], a:'Un volcán es una abertura en la corteza terrestre por donde sale magma (roca fundida). Cuando el magma alcanza la superficie se llama lava. Tipos: activos (pueden erupcionar), dormidos (no han erupcionado en mucho tiempo pero pueden), extintos (no erupcionarán más). Hay ~1.500 volcanes activos en el mundo. El 75% están en el "Círculo de Fuego" del Pacífico. El más famoso: Vesubio (Pompeya), Krakatoa (1883), Monte Santa Helena (1980).'},

  // ═══ HISTORIA ═══
  {k:['historia','antigua','civilización','egipcio','romano','griego','mesopotamia','prehistoria'], a:'Las primeras civilizaciones surgieron en Mesopotamia (actual Irak) entre el Tigris y Éufrates hace ~6.000 años. El Antiguo Egipto (3.100 a.C.) construyó las pirámides de Giza. La Antigua Grecia (siglo V a.C.) creó la democracia, filosofía y teatro. El Imperio Romano (27 a.C.-476 d.C.) dominó el Mediterráneo, legando derecho, latín e ingeniería. El Imperio Bizantino continuó hasta 1453.'},
  {k:['guerra','mundial','primera','segunda','conflicto','bélico','batalla','ejército','aliado','eje'], a:'Primera Guerra Mundial (1914-1918): 17 millones de muertos. Causa: asesinato del archiduque Francisco Fernando. Segunda Guerra Mundial (1939-1945): 60-80 millones de muertos, el conflicto más mortífero. Aliados (EE.UU., Reino Unido, URSS, Francia) vs Eje (Alemania, Italia, Japón). Terminó con bombas atómicas sobre Hiroshima y Nagasaki (agosto 1945). La Guerra Fría (1947-1991) enfrentó a EE.UU. y URSS sin combate directo.'},
  {k:['colón','cristóbal','descubrimiento','américa','1492','españa','indias','nuevo','mundo'], a:'Cristóbal Colón descubrió América el 12 de octubre de 1492, llegando a las Bahamas (Guanahaní). Zarpoó desde Palos de la Frontera (España) con tres carabelas: La Niña, La Pinta y La Santa María. Buscaba una ruta a las Indias por el oeste. Este evento inició la colonización europea de América, el intercambio colombino (cultivos, animales, enfermedades entre continentes) y el Imperio Español en el Nuevo Mundo.'},
  {k:['independencia','américa','latina','libertador','simón','bolívar','san','martín','hidalgo','morelos'], a:'Las independencias latinoamericanas ocurrieron entre 1810 y 1825. Simón Bolívar ("El Libertador") lideró las independencias de Venezuela, Colombia, Ecuador, Perú y Bolivia. José de San Martín liberó Argentina, Chile y Perú. Miguel Hidalgo inició la independencia de México (Grito de Dolores, 16 sep 1810). José de San Martín cruzó los Andes (1817) para liberar Chile. La batalla de Ayacucho (1824) selló la independencia sudamericana.'},
  {k:['revolución','francesa','1789','francesa','francesa','nacional','toma','bastilla','derechos','hombre','ciudadano'], a:'La Revolución Francesa (1789-1799) fue un período de transformación social y política radical. Inició con la Toma de la Bastilla (14 julio 1789). La Asamblea Nacional aprobó la Declaración de los Derechos del Hombre y del Ciudadano (libertad, igualdad, fraternidad). Luis XVI fue ejecutado en 1793. Napoleón Bonaparte tomó el poder en 1799 y se convirtió en emperador. La revolución influyó en movimientos democráticos en todo el mundo.'},
  {k:['mayas','aztecas','incas','precolombino','mesoamérica','tenochtitlán','machu','picchu','cuzco','teotihuacán'], a:'Grandes civilizaciones precolombinas: 1) Mayas (México y Centroamérica): avanzados en matemáticas, astronomía y escritura jeroglífica. Crearon el cero y un calendario preciso. 2) Aztecas (México central): fundaron Tenochtitlán (hoy CDMX). Imperio poderoso hasta la llegada de los españoles (1521). 3) Incas (Perú, Ecuador, Bolivia, Chile): el imperio más grande de América precolombina. Construyeron Machu Picchu y una red de caminos (Qhapaq Ñan) de 40.000 km.'},
  {k:['renacimiento','arte','cultura','europa','siglo','xv','xvi','medici','florencia','humanismo'], a:'El Renacimiento (siglos XIV-XVI) fue un movimiento cultural y artístico que surgió en Italia (Florencia) y se extendió por Europa. Caracterizado por el humanismo (valor del ser humano), redescubrimiento de la cultura clásica grecorromana, e innovaciones en arte, ciencia y literatura. Grandes figuras: Leonardo da Vinci (Mona Lisa, La Última Cena), Miguel Ángel (Capilla Sixtina, David), Rafael (Escuelas de Atenas), Dante (La Divina Comedia).'},
  {k:['edad','media','medieval','castillo','caballero','feudo','señor','vasallo','sirviente','siervo'], a:'La Edad Media (siglos V-XV) abarca desde la caída del Imperio Romano (476) hasta el descubrimiento de América (1492). Se caracterizó por el sistema feudal (rey, nobles, clero, campesinos), castillos, caballeros, y el poder de la Iglesia católica. La Peste Negra (1347-1351) mató a un tercio de la población europea. Las Cruzadas fueron expediciones militares cristianas a Tierra Santa. La sociedad estaba organizada en estamentos.'},
  {k:['imperio','romano','roma','césar','augusto','pompeya','coliseo','legión','gladiador','acueducto'], a:'El Imperio Romano (27 a.C.-476 d.C.) fue el más extenso de la antigüedad, abarcando el Mediterráneo, Europa occidental, norte de África y Oriente Medio. Augusto fue el primer emperador. Legados: el derecho romano (base del derecho occidental), el latín (origen de lenguas romances), el calendario juliano, la ingeniería (acueductos, carreteras, el Coliseo), el hormigón. Roma cayó en 476 d.C. por invasiones bárbaras y crisis internas.'},

  // ═══ GEOGRAFÍA ═══
  {k:['españa','país','ibérico','península','madrid','barcelona','valencia','andalucía','castilla','galicia','país vasco','comunidad'], a:'España es un país del suroeste de Europa, en la Península Ibérica. Capital: Madrid (3.2M hab). 47 millones de habitantes. 17 comunidades autónomas + 2 ciudades autónomas (Ceuta, Melilla). Idiomas: español (oficial), catalán, gallego, euskera. Limita con Francia, Andorra, Portugal, Marruecos. Moneda: euro. Miembro de la UE y la OTAN.'},
  {k:['méxico','país','mexicano','cdmx','mexico','tenochtitlán','azteca','maya','chiapas','yucatán','oaxaca','guadalajara'], a:'México es un país de América del Norte. Capital: CDMX (Ciudad de México, 9M hab, 22M área metropolitana). 128 millones de habitantes. 32 estados. Idiomas: español y 68 lenguas indígenas (náhuatl, maya, zapoteco, mixteco). Famoso por: su gastronomía (tacos, mole, tequila), playas (Cancún, Puerto Vallarta), ruinas prehispánicas (Teotihuacán, Chichén Itzá), Día de Muertos, y su biodiversidad.'},
  {k:['argentina','país','argentino','buenos','aires','patagonia','tango','mate','perón','messi','maradona','pampas'], a:'Argentina es un país de América del Sur. Capital: Buenos Aires (3M hab, 15M área metropolitana). 46 millones de habitantes. 23 provincias + CABA. Famoso por: el tango, el asado, el mate, el fútbol (Messi, Maradona), la Patagonia (glaciares, Torres del Paine), las cataratas del Iguazú, el vino Malbec. 8º país más grande del mundo (2.78M km²). Monte Aconcagua (6.961m), el pico más alto de América.'},
  {k:['colombia','país','colombiano','bogotá','medellín','cali','barranquilla','café','salsa','gabriel','garcía','marquez','esmeralda'], a:'Colombia es un país de América del Sur. Capital: Bogotá (8M hab). 51 millones de habitantes. 32 departamentos. Famoso por: el café colombiano, la salsa, Gabriel García Márquez (Premio Nobel, "Cien años de soledad"), la biodiversidad (2º país más biodiverso del mundo), esmeraldas, las playas de Cartagena y Santa Marta, el río Caño Cristales ("río de los 5 colores"). Costas en Pacífico y Caribe.'},
  {k:['chile','país','chileno','santiago','patagonia','atacama','neruda','pascua','moáis','torres','paine','pablo'], a:'Chile es un país de América del Sur. Capital: Santiago (6M hab). 19 millones de habitantes. 16 regiones. Es el país más largo del mundo (4.300 km de norte a sur). Incluye: desierto de Atacama (el más árido), la Patagonia, Isla de Pascua (moáis), Torres del Paine, glaciares, viñedos (vino chileno). Pablo Neruda, Premio Nobel de Literatura (1971), es su poeta más famoso. Principal recurso: cobre (mayor productor mundial).'},
  {k:['perú','país','peruano','lima','machu','picchu','inca','ceviche','cuzco','kusko','cusco','nazca','líneas'], a:'Perú es un país de América del Sur. Capital: Lima (10M hab). 33 millones de habitantes. 24 departamentos. Famoso por: Machu Picchu (maravilla mundial, ciudadela inca), el ceviche (plato nacional), las líneas de Nazca, la amazonía peruana (60% del territorio), el lago Titicaca (lago navegable más alto del mundo, 3.812m). Gastronomía reconocida mundialmente. Antiguo hogar del Imperio Inca.'},
  {k:['venezuela','país','venezolano','caracas','simón','bolívar','petróleo','ángel','salto','cascada','maracaibo','isla','margarita'], a:'Venezuela es un país de América del Sur. Capital: Caracas (3M hab). 28 millones de habitantes. 23 estados + Distrito Capital. Posee las reservas de petróleo más grandes del mundo. El Salto Ángel (Kerepakupai Vená) en el Parque Nacional Canaima es la cascada más alta del mundo (979m). Simón Bolívar nació en Caracas. El lago de Maracaibo es el más grande de Sudamérica. Conocido por sus playas, la Isla de Margarita y los Andes venezolanos.'},
  {k:['brasil','país','brasileño','brasilia','rio','janeiro','são','paulo','amazonas','selva','carnaval','samba','fútbol','pelé','ney'], a:'Brasil es el país más grande de América del Sur (8.5M km²) y el 5º del mundo. Capital: Brasilia. 215 millones de habitantes. 26 estados + Distrito Federal. Idioma: portugués. La Amazonía brasileña es el bosque tropical más grande del mundo. Famoso por: el carnaval de Río, la samba, el fútbol (Pelé, Neymar), Cristo Redentor, las playas de Copacabana e Ipanema. Es la mayor economía de América Latina.'},
  {k:['eeuu','ee.uu.','estados','unidos','américa','usa','washington','nueva','york','los ángeles','california','texas','florida'], a:'Estados Unidos es un país de América del Norte. Capital: Washington D.C. Población: 335 millones (3º del mundo). 50 estados. 9.8M km² (4º más grande). Famoso por: Nueva York (Estatua de la Libertad), Los Ángeles (Hollywood), San Francisco (Golden Gate), Las Vegas, el Gran Cañón, los parques nacionales. Principal economía mundial. Idioma de facto: inglés. Fundado en 1776 con la Declaración de Independencia.'},
  {k:['china','país','chino','pequín','shanghai','gran','muralla','ejército','terracota','confucio','mandarín'], a:'China (República Popular China) es el país más poblado del mundo (~1.400 millones) y 4º más grande (9.6M km²). Capital: Pekín (Beijing). 23 provincias + regiones autónomas. Partido Comunista de China. La Gran Muralla China (~21.000 km) es una de las 7 maravillas del mundo. El Ejército de Terracota (Xi\'an) data del 210 a.C. El mandarín es el idioma más hablado del mundo. Mayor exportador mundial y 2ª economía más grande.'},
  {k:['japón','país','japonés','tokio','kioto','osaka','fuji','sushi','samurái','anime','manga','sony','toyota'], a:'Japón es un país insular de Asia Oriental. Capital: Tokio (14M hab, 37M área metropolitana). 125 millones de habitantes. 4 islas principales: Honshū, Hokkaidō, Kyūshū, Shikoku. Famoso por: el Monte Fuji (3.776m), los templos de Kioto, el sushi, los samuráis, el anime (Naruto, Dragon Ball), manga, tecnología (Sony, Toyota, Nintendo). Es una de las economías más avanzadas. Conocido por su cultura de respeto y puntualidad.'},
  {k:['inglaterra','reino','unido','londres','inglés','británico','reina','rey','parlamento','big','ben','támesis'], a:'Reino Unido (UK) es un país de Europa occidental formado por Inglaterra, Escocia, Gales e Irlanda del Norte. Capital: Londres (9M hab). 67 millones de habitantes. Monarquía parlamentaria con el rey Carlos III como jefe de estado. Famoso por: el Big Ben, el Támesis, Stonehenge, la monarquía, los Beatles, Shakespeare, la revolución industrial, el fútbol (Premier League), y la BBC. Idioma: inglés.'},
  {k:['francia','país','francés','parís','torre','eiffel','louvre','museo','vino','baguette','croissant','napoleón'], a:'Francia (República Francesa) es un país de Europa occidental. Capital: París (11M área metropolitana). 68 millones de habitantes. 18 regiones. Famoso por: la Torre Eiffel, el Museo del Louvre (Mona Lisa), la gastronomía (vino, queso, baguette, croissant), la moda (París capital de la moda), Napoleón Bonaparte, la Revolución Francesa, el idioma francés y la Riviera Francesa. Miembro fundador de la UE.'},
  {k:['capital','mundo','países','ciudad','grande','población'], a:'Las ciudades más pobladas del mundo: 1) Tokio (Japón) ~37M, 2) Delhi (India) ~32M, 3) Shanghái (China) ~28M, 4) São Paulo (Brasil) ~22M, 5) Ciudad de México ~22M, 6) El Cairo (Egipto) ~21M, 7) Dhaka (Bangladesh) ~21M, 8) Mumbai (India) ~21M, 9) Pekín (China) ~20M, 10) Osaka (Japón) ~19M. La ciudad más antigua habitada continuamente es Jericó (Cisjordania, ~11.000 años).'},

  // ═══ TECNOLOGÍA ═══
  {k:['inteligencia','artificial','ia','machine','learning','aprendizaje','automático','red','neuronal','deep','algorithm','algoritmo','gpt','llm'], a:'La Inteligencia Artificial (IA) es la simulación de inteligencia humana por máquinas. Tipos principales: 1) Machine Learning: algoritmos que aprenden de datos. 2) Deep Learning: redes neuronales con múltiples capas. 3) NLP: procesamiento de lenguaje natural. 4) Visión artificial. 5) IA generativa (crea texto, imágenes, música). Aplicaciones: asistentes virtuales, diagnóstico médico, autos autónomos, traducción, recomendaciones. X0GPT es un ejemplo de IA conversacional que funciona localmente.'},
  {k:['programación','programar','lenguaje','código','software','desarrollo','programmer','coder','ingeniería'], a:'La programación es crear instrucciones para computadoras. Lenguajes por uso: 1) Web: JavaScript, TypeScript, HTML/CSS. 2) Ciencia de datos e IA: Python, R. 3) Apps móviles: Kotlin (Android), Swift (iOS), React Native. 4) Sistemas/rendimiento: C, C++, Rust. 5) Empresarial: Java, C#. 6) Backend: Go, Python, Node.js, PHP. Para empezar: elige un lenguaje (recomiendo Python o JavaScript), practica con proyectos pequeños, y usa recursos gratuitos.'},
  {k:['javascript','js','lenguaje','programación','web','frontend','node','react','angular','vue','ecmascript','jquery'], a:'JavaScript (JS) es el lenguaje de programación de la web. Creado por Brendan Eich en 1995 en solo 10 días. Es multiparadigma: orientado a objetos, funcional, imperativo. Se ejecuta en el navegador (cliente) y en servidores (Node.js). Frameworks populares: React (Meta), Angular (Google), Vue.js. Es el lenguaje más utilizado según encuestas de Stack Overflow. Ecosistema enorme con npm (millones de paquetes). ES6+ introdujo clases, arrow functions, promesas y módulos.'},
  {k:['python','piton','lenguaje','programación','django','flask','pandas','numpy','tensorflow','pytorch'], a:'Python es un lenguaje de programación creado por Guido van Rossum (1991). Conocido por su sintaxis limpia y legible (el código se lee como inglés). Usos: ciencia de datos (Pandas, NumPy), IA/ML (TensorFlow, PyTorch, scikit-learn), desarrollo web (Django, Flask), automatización, scripts, educación. Es el lenguaje más recomendado para principiantes. Versión actual: Python 3.12+.'},
  {k:['internet','web','navegador','browser','chrome','firefox','edge','safari','http','https','url','dominio','servidor','dns'], a:'Internet es una red global de computadoras interconectadas. La World Wide Web (WWW) fue creada por Tim Berners-Lee en 1989 en el CERN. Navegadores: Chrome (65% cuota), Safari (19%), Firefox (3%), Edge (5%), Opera (2%). HTTPS cifra la comunicación entre navegador y servidor. Los DNS convierten nombres de dominio (google.com) en direcciones IP. HTML, CSS y JavaScript son los pilares de la web.'},
  {k:['ciberseguridad','hacker','seguridad','informática','virus','malware','ataque','proteger','contraseña','phishing','ransomware'], a:'Consejos de ciberseguridad: 1) Usa contraseñas únicas y fuertes (gestor como Bitwarden o LastPass). 2) Activa autenticación de dos factores (2FA). 3) Mantén todo actualizado (SO, apps). 4) No hagas clic en enlaces sospechosos (phishing). 5) Usa antivirus (Malwarebytes, Windows Defender). 6) Haz copias de seguridad (regla 3-2-1). 7) No uses redes WiFi públicas sin VPN. 8) Desconfía de correos con urgencia o archivos adjuntos inesperados.'},
  {k:['blockchain','bitcoin','criptomoneda','ethereum','cadena','bloque','minería','nft','web3','crypto','solana','cardano'], a:'Blockchain (cadena de bloques) es una tecnología de registro distribuido creada en 2008 para Bitcoin (por el misterioso Satoshi Nakamoto). Es una base de datos descentralizada e inmutable. Bitcoin (BTC) es la primera criptomoneda (~21 millones máximo). Ethereum introdujo contratos inteligentes. NFTs (tokens no fungibles) representan propiedad digital única. Web3 busca una internet descentralizada. Riesgos: volatilidad extrema, estafas, consumo energético en minería PoW.'},
  {k:['hardware','computadora','pc','ordenador','laptop','portátil','procesador','cpu','ram','disco','ssd','gpu','placa','madre'], a:'Componentes de PC: CPU (procesador): el cerebro. Intel (Core i3/i5/i7/i9) o AMD (Ryzen 3/5/7/9). RAM: memoria temporal (8GB mínimo, 16GB recomendado). SSD: almacenamiento rápido (256GB-1TB). GPU: tarjeta gráfica (NVIDIA GeForce, AMD Radeon). Placa madre: conecta todo. Fuente de poder: suministra energía. Para una PC básica de oficina: i5/Ryzen5, 16GB RAM, SSD 512GB. Para gaming: añade GPU dedicada. Para edición: más RAM y buena GPU.'},
  {k:['red','social','facebook','instagram','twitter','tiktok','whatsapp','youtube','linkedin','señal','telegram','seguidor'], a:'Redes sociales: Facebook (Meta, 3,000M usuarios), YouTube (2,500M), WhatsApp (2,000M), Instagram (2,000M), TikTok (1,500M), WeChat (1,300M), Telegram (800M), Snapchat (750M), X/Twitter (550M), LinkedIn (900M), Pinterest (450M). Consejos: cuida tu privacidad, no compartas datos sensibles, verifica información antes de compartir, limita tiempo de uso, bloquea cuentas sospechosas.'},
  {k:['privacidad','dato','personal','proteger','información','privado','anonimato','huella','digital','seguimiento','rastreo','cookie'], a:'Protege tu privacidad digital: 1) Contraseñas diferentes para cada servicio. 2) 2FA donde sea posible. 3) Revisa permisos de apps. 4) Usa VPN en redes públicas. 5) Modo incógnito no es anónimo (solo no guarda historial local). 6) Borra cookies periódicamente. 7) Usa DuckDuckGo o Brave para buscar con privacidad. 8) No compartas ubicación en tiempo real. 9) Revisa qué datos tienen las apps sobre ti.'},

  // ═══ SALUD ═══
  {k:['fiebre','temperatura','gripe','resfriado','tos','garganta','dolor','cuerpo','enfermo','enfermedad','síntoma','virus','covid'], a:'Para síntomas de resfriado o fiebre: 1) Descansa y mantente hidratado (agua, té, caldo). 2) Toma paracetamol o ibuprofeno para la fiebre (sigue indicaciones del prospecto). 3) Bebe líquidos calientes. 4) Ventila la habitación. 5) Lava tus manos frecuentemente. 6) Si la fiebre supera 39°C o dura más de 3 días, consulta a un médico. No automediques antibióticos (no sirven para virus). Si es COVID-19, aíslate y hazte una prueba.'},
  {k:['covid','coronavirus','pandemia','virus','sars','covid19','cuarentena','vacuna'], a:'El COVID-19 (SARS-CoV-2) es una enfermedad respiratoria altamente contagiosa. Síntomas: fiebre, tos seca, fatiga, pérdida de gusto/olfato. Prevención: vacunación completa + refuerzos, mascarilla en espacios cerrados, lavado de manos, ventilación. La OMS declaró el fin de la emergencia global en mayo 2023, pero el virus sigue circulando. Grupos de riesgo: adultos mayores, personas con enfermedades crónicas. Si tienes síntomas, usa mascarilla y evita contagiar.'},
  {k:['dolor','cabeza','migraña','cefalea','tensional','jaqueca'], a:'Para aliviar el dolor de cabeza: 1) Descansa en un lugar oscuro y silencioso. 2) Aplica compresas frías en la frente. 3) Masajea suavemente sienes y cuello. 4) Toma ibuprofeno o paracetamol si es necesario. 5) Bebe agua (la deshidratación causa dolores de cabeza). 6) Evita pantallas y cafeína. 7) Si es migraña, identifica y evita tus desencadenantes (luces brillantes, ruidos fuertes, ciertos alimentos). Consulta a un médico si es recurrente o muy intenso.'},
  {k:['herida','corte','sangrado','sangre','lastimadura','raspón','primeros','auxilios','herida'], a:'Primeros auxilios para heridas: 1) Lávate las manos. 2) Limpia la herida con agua y jabón suave. 3) Aplica presión directa con gasa estéril para detener sangrado. 4) Desinfecta con agua oxigenada o povidona yodada (evita el alcohol directo, duele y daña tejido). 5) Cubre con apósito o venda. 6) Cambia el apósito diariamente. 7) Señales de infección: enrojecimiento, hinchazón, pus, fiebre. Si el sangrado no se detiene tras 10 minutos, busca atención médica.'},
  {k:['quemadura','quemo','fuego','calor','ardiente','llama','escaldadura','solar','sol'], a:'Para quemaduras leves (1er grado): 1) Enfría la zona con agua fría (no hielo directo) 10-15 minutos. 2) No apliques mantequilla, pasta dental, aceite ni hielo. 3) Cubre con gasa estéril. 4) Toma ibuprofeno para el dolor. 5) No revientes las ampollas (protegen la piel). Para quemaduras graves (2do/3er grado, ampollas grandes, piel carbonizada): busca atención médica inmediata. Para quemaduras solares: aloe vera, hidratación, evitar más exposición.'},
  {k:['rcp','reanimación','cardíaco','corazón','respiración','desmayo','inconsciente','paro','cardiorrespiratorio'], a:'RCP básica (Reanimación Cardiopulmonar): 1) Verifica que la persona esté inconsciente y no respire. 2) Pide ayuda y llama a emergencias (112 o 911). 3) Coloca a la persona boca arriba en superficie firme. 4) Arrodíllate a su lado. 5) Entrelaza tus manos en el centro del pecho (mitad inferior del esternón). 6) Comprime fuerte y rápido: 100-120 compresiones/minuto, ~5cm de profundidad. 7) Continúa hasta que llegue ayuda o la persona reaccione. No necesitas respiración boca a boca (solo compresiones).'},
  {k:['asfixia','atragantamiento','ahogo','no puede','respirar','comida','tragar','heimlich'], a:'Maniobra de Heimlich para atragantamiento: 1) Colócate detrás de la persona. 2) Abrázala alrededor de la cintura. 3) Haz un puño y colócalo justo arriba del ombligo. 4) Agarra tu puño con la otra mano. 5) Empuja hacia adentro y arriba con movimientos rápidos y fuertes. 6) Repite hasta que expulse el objeto o la persona pierda el conocimiento. Si está solo: usa el respaldo de una silla para presionar tu abdomen. Si pierde el conocimiento, inicia RCP.'},
  {k:['alimentación','saludable','dieta','nutrición','comida','comer','nutriente','vitamina','proteína','carbohidrato','grasa','fibra','mineral'], a:'Alimentación saludable: 1) 5 porciones de frutas y verduras al día. 2) Legumbres (lentejas, garbanzos, frijoles) al menos 2-3 veces/semana. 3) Cereales integrales (arroz, pan, pasta). 4) Proteínas magras (pollo, pescado, huevos, tofu, legumbres). 5) Grasas saludables (aguacate, nueces, aceite de oliva). 6) Limita: azúcar añadido, sal, grasas saturadas, ultraprocesados. 7) Bebe 1.5-2 litros de agua al día. 8) Cocina en casa todo lo posible.'},
  {k:['ejercicio','físico','gimnasio','entrenar','pesa','cardio','fuerza','flexibilidad','rutina','entrenamiento','deporte'], a:'Rutina básica sin equipo (3-4 veces/semana): 1) Calentamiento 5 min (saltos, círculos de brazos). 2) Sentadillas: 3x15. 3) Flexiones: 3x al fallo (o de rodillas). 4) Plancha: 3x30 seg. 5) Zancadas: 3x12 cada pierna. 6) Burpees: 3x10. 7) Estiramientos 5 min. Beneficios: mejora cardiovascular, fortalece músculos y huesos, reduce estrés, mejora sueño, controla peso. La OMS recomienda 150 min de actividad moderada o 75 min intensa a la semana.'},
  {k:['salud','mental','ansiedad','depresión','estrés','ansioso','triste','preocupado','terapia','psicólogo','psiquiatra','bienestar','emocional'], a:'Cuida tu salud mental: 1) Habla con alguien de confianza sobre cómo te sientes. 2) Practica mindfulness o meditación (5-10 min al día). 3) Haz ejercicio regularmente. 4) Duerme 7-9 horas diarias. 5) Limita redes sociales y noticias negativas. 6) Mantén rutinas saludables (horarios, alimentación). 7) Conéctate con personas que te hacen bien. 8) Si necesitas ayuda, buscar terapia es valiente y efectivo. No estás solo. Líneas de ayuda: 024 (España), 800 222 100 (México).'},
  {k:['dormir','sueño','insomnio','descansar','cama','despertar','cansado','fatiga','nocturno','melatonina'], a:'Higiene del sueño: 1) Horario regular (acostarte y levantarte a la misma hora, incluso fines de semana). 2) Evita pantallas (luz azul) 1-2 horas antes de dormir. 3) Habitación oscura, fresca (18-20°C) y silenciosa. 4) No cafeína después de las 4pm (el café, té, chocolate, refrescos). 5) Cena ligero 2-3 horas antes. 6) Haz ejercicio durante el día. 7) Rutina relajante pre-sueño (leer, música suave, baño tibio). 8) Si no puedes dormir, levántate y haz algo tranquilo hasta sentir sueño.'},
  {k:['meditar','meditación','mindfulness','atención','plena','respiración','relajación','zen','yoga','consciencia'], a:'Meditación guiada (5 min): 1) Siéntate cómodo con espalda recta. 2) Cierra los ojos. 3) Respira profundamente 3 veces. 4) Observa tu respiración natural (entra y sale). 5) Cuando te distraigas (normal), suavemente regresa a la respiración. 6) No te juzgues. 7) Continúa 5 min. Beneficios: reduce estrés y ansiedad, mejora concentración y memoria, aumenta bienestar emocional, mejora sueño. Apps: Headspace, Calm, Meditopia. La práctica regular es más importante que la duración.'},
  {k:['médico','medicina','doctor','enfermero','hospital','clínica','consulta','diagnóstico','tratamiento'], a:'Importante: Soy un asistente de IA con información general, NO un médico. Si tienes síntomas, consulta a un profesional de la salud. La automedicación puede ser peligrosa (efectos secundarios, interacciones, dosis incorrectas). En emergencias, llama a tu número local (112 España, 911 México/EEUU). Puedo proporcionar información general sobre salud, pero nunca debe sustituir el consejo médico profesional.'},

  // ═══ SUPERVIVENCIA ═══
  {k:['agua','potable','beber','hidratación','sed','purificar','hervir','filtro','potabilizar','gotas','yodo'], a:'Métodos para purificar agua (supervivencia): 1) Hervir: lleva a ebullición durante 5-10 minutos (mata bacterias, virus y parásitos). 2) Filtros: portátiles (LifeStraw, Sawyer) o de carbón casero. 3) Pastillas potabilizadoras de yodo o cloro (sigue instrucciones, 30 min de espera). 4) Exposición solar: botella PET al sol 6+ horas (SODIS, mata patógenos con UV). 5) Destilación: hervir y condensar vapor. NO bebas agua de fuentes desconocidas sin tratar. Un adulto necesita ~2 litros/día.'},
  {k:['fuego','encender','llama','hoguera','prender','fosforo','yesquero','pedernal','lupa','fricción'], a:'Cómo encender fuego sin fósforos: 1) Arco de fricción: madera blanda (base) + madera dura (broca), girar rápido para crear brasa. 2) Lupa o lente: enfoca luz solar en yesca seca. 3) Pedernal y acero: golpea para crear chispas. 4) Batería y lana de acero: conecta los bornes, la lana se enciende. 5) Botella con agua: actúa como lente. La yesca debe ser fina y seca (corteza de abedul, hojas secas, pasto, pelusa de algodón). Prepara leña de diferentes tamaños antes de encender.'},
  {k:['refugio','casa','construir','dormir','protegerse','intemperie','lluvia','viento','frio','frío','aislamiento'], a:'Refugio de supervivencia: 1) Ubicación: lugar seco, plano, protegido del viento, cerca de agua y leña pero no en cauce seco. 2) Lean-to (inclinado): rama horizontal entre 2 árboles, ramas inclinadas a 45°, cubrir con hojas, pasto, cortezas en capas gruesas (como tejas). 3) Piso: eleva con ramas y hojas para aislar del frío suelo. 4) Pared de nieve (si hay): los iglús mantienen calor. 5) Si tienes lona o plástico, úsalo como cubierta. El aislamiento del suelo es tan importante como el techo.'},
  {k:['comida','alimento','comer','supervivencia','comestible','cazar','pescar','trampa','plantas'], a:'Alimentos de supervivencia: 1) Plantas comestibles comunes: diente de león (toda la planta), trébol, ortiga (cocinar para quitar pelos urticantes), berros, llantén. 2) Insectos comestibles: grillos, saltamontes, hormigas (cocinar siempre, son ricos en proteína). 3) Pesca: anzuelo improvisado (clip, espina, alfiler), sedal con cuerda, usar gusanos o insectos como cebo. 4) Trampas: lazos simples en senderos de animales. REGLA DE ORO: si no estás 100% seguro de que una planta es comestible, NO la comas.'},
  {k:['navegación','orientarse','perder','brújula','mapa','dirección','norte','sur','este','oeste','estrella','polar','musgo'], a:'Orientación sin brújula: 1) Sol: sale por el Este, se pone por el Oeste. Al mediodía está al Sur (hemisferio norte). 2) Estrella Polar (Norte): sigue las 2 últimas estrellas del carro de la Osa Mayor. 3) Reloj analógico: la bisectriz entre la hora y las 12 apunta al Sur (hemisferio norte). 4) Musgo: crece más en el lado norte de árboles (hemisferio norte, donde hay menos sol). 5) Ramas: suelen ser más largas hacia el sur. 6) Si tienes GPS o mapas offline en tu teléfono, úsalos.'},
  {k:['tormenta','rayo','relámpago','trueno','huracán','ciclón','tornado','desastre','natural','inundación','sequía'], a:'Seguridad durante tormentas: 1) Busca refugio en edificio o vehículo cerrado. 2) Aléjate de árboles altos, postes, cuerpos de agua. 3) No uses aparatos eléctricos conectados. 4) Si estás al aire libre sin refugio: agáchate en cuclillas, pies juntos, cabeza baja (no te acuestes en el suelo). 5) Espera 30 minutos después del último trueno para salir. 6) La regla 30-30: si entre relámpago y trueno hay menos de 30 segundos, el rayo está peligrosamente cerca.'},
  {k:['terremoto','sismo','temblor','movimiento','tierra','epicentro','replica','alerta'], a:'Durante un terremoto: 1) Agáchate, cúbrete, sujétate (drop, cover, hold). 2) Métete debajo de mesa resistente. 3) Aléjate de ventanas, espejos, lámparas, muebles altos. 4) Si estás en cama, cúbrete cabeza con almohada. 5) No uses ascensores. 6) Si estás en la calle, aléjate de edificios, postes, cables. 7) Si conduces, estaciónate lejos de puentes, túneles y edificios altos. Después: revisa heridos, corta gas y electricidad si hay daños, prepárate para réplicas, ten agua y linterna.'},

  // ═══ COCINA ═══
  {k:['receta','cocinar','cocina','plato','comida','ingrediente','preparar','chef','gastronomía'], a:'Receta básica: Arroz blanco perfecto (4 personas). Ingredientes: 1 taza arroz, 2 tazas agua, sal, 1 cda aceite. Preparación: 1) Lava el arroz hasta que el agua salga clara (quita almidón). 2) Calienta el aceite en olla. 3) Sofríe el arroz 2 minutos. 4) Agrega agua hirviendo y sal. 5) Tapa y cocina a fuego bajo 18-20 minutos. 6) Apaga y deja reposar 5 minutos (no destapes). 7) Esponja con tenedor. ¡Perfecto! El secreto: NO remover durante la cocción y respetar la proporción 2:1 (agua:arroz).'},
  {k:['huevo','cocinar','hervido','frito','revuelto','tortilla','poche','cocción'], a:'Técnicas para cocinar huevos: 1) Hervido: agua hirviendo, 6 min (líquido), 8 min (medio), 10 min (duro). Enfriar en agua fría. 2) Frito: sartén con aceite caliente, cascar suavemente, cocinar 2-3 min. 3) Revuelto: batir, sartén con mantequilla, cocinar a fuego medio removiendo. 4) Tortilla española: huevos batidos con patatas fritas y cebolla. 5) Poche: agua con vinagre hirviendo, cascar huevo, cocinar 3 min. El huevo fresco se hunde en agua, el viejo flota.'},
  {k:['paella','valenciana','español','valencia','arroz','azafrán','mariscos','pollo','conejo','socarrat'], a:'Paella valenciana tradicional: Ingredientes: arroz bomba, pollo, conejo, judía verde, garrofón, azafrán, pimentón dulce, aceite de oliva, agua, sal. Preparación: 1) Sofríe la carne en aceite caliente hasta dorar. 2) Añade verduras y pimentón. 3) Agrega agua caliente y azafrán. 4) Cuando hierva, añade el arroz en forma de cruz. 5) Cocina 10 min a fuego fuerte, 8 min a fuego medio. 6) Deja reposar 5 min tapado con papel aluminio. El socarrat (arroz tostado del fondo) es la parte más codiciada.'},
  {k:['taco','mexicano','comida','tortilla','carne','salsa','guacamole','cilantro','cebolla','limón','al','pastor','carnitas','barbacoa'], a:'Tipos de tacos mexicanos: 1) Al pastor: carne de cerdo adobada con achiote, cocinada en trompo, con piña. 2) Carnitas: cerdo confitado en manteca hasta que queda tierno. 3) Barbacoa: cordero o res cocida bajo tierra en pencas de maguey. 4) Canasta: tacos sudados (papas, frijoles, chicharrón). 5) Pescado: estilo Baja California, pescado empanizado con repollo y crema. Base: tortilla de maíz caliente, relleno, cebolla, cilantro, salsa, limón. La salsa puede ser roja (picante) o verde (tomatillo).'},
  {k:['sushi','japonés','arroz','pescado','salmon','atún','nori','wasabi','jengibre','shoyu'], a:'El sushi es un plato japonés de arroz avinagrado con pescado crudo u otros ingredientes. Tipos: 1) Nigiri: bola de arroz con pescado encima. 2) Maki: rollo envuelto en alga nori. 3) Uramaki: arroz por fuera, alga por dentro. 4) Sashimi: solo pescado crudo en láminas (sin arroz). 5) Temaki: cono de alga relleno. Acompañamientos: wasabi (rábano picante), jengibre encurtido (para limpiar el paladar), shoyu (salsa de soja). El arroz debe estar a temperatura ambiente, no frío.'},

  // ═══ FINANZAS ═══
  {k:['dinero','finanzas','ahorrar','invertir','presupuesto','economía','gastos','ingresos','banco','cuenta','deuda'], a:'Regla financiera 50/30/20: 1) 50% de ingresos para necesidades (alquiler, comida, transporte, servicios). 2) 30% para deseos (ocio, viajes, restaurantes). 3) 20% para ahorro e inversión. Consejos: fondo de emergencia de 3-6 meses de gastos, paga deudas de alto interés primero (tarjetas de crédito), invierte temprano para interés compuesto, lleva registro de gastos (apps como Fintonic, YNAB o simple Excel). Educación financiera es clave para la libertad financiera.'},
  {k:['invertir','inversión','bolsa','acciones','fondo','índice','renta','variable','fija','riesgo','rentabilidad','dividendo','etf','broker'], a:'Inversión para principiantes: 1) Fondo de emergencia primero (3-6 meses de gastos). 2) ETFs indexados (como S&P 500 o MSCI World): diversificados, bajo costo, siguen al mercado. 3) Interés compuesto: cuanto más tiempo, mejor (invertir 100€/mes desde los 25 años vs 35 años marca una gran diferencia). 4) Riesgo y rentabilidad van de la mano. 5) DCA (promedio de costo en dólares): invierte una cantidad fija cada mes. 6) No inviertas en lo que no entiendes. 7) Consulta a un asesor financiero.'},
  {k:['impuesto','declarar','hacienda','sat','irpf','iva','tributo','renta','fiscal','contador','contable'], a:'Los impuestos son contribuciones obligatorias al Estado para financiar servicios públicos (educación, salud, infraestructura). En España: IRPF (Impuesto sobre la Renta), IVA (21% general, 10% reducido, 4% superreducido), Sociedades. En México: ISR (Impuesto Sobre la Renta), IVA (16%), declaración anual. Las fechas y tasas varían por país. Recomendación: lleva contabilidad ordenada (ingresos y gastos) y consulta a un contador profesional. En muchos países hay deducciones fiscales que puedes aprovechar.'},
  {k:['criptomoneda','bitcoin','ethereum','solana','cardano','invertir','compra','venta','minería','staking'], a:'Invertir en criptomonedas conlleva alto riesgo por su volatilidad extrema (Bitcoin ha caído 80% varias veces). Reglas: 1) Solo invierte lo que puedas permitirte perder. 2) Compra en exchanges regulados (Coinbase, Kraken, Binance). 3) Guarda en wallet personal (Ledger, Trezor para frío; MetaMask para caliente). 4) Haz DCA (compra periódica). 5) No inviertas por FOMO. 6) El mercado es 24/7 y muy volátil. 7) Infórmate bien antes de invertir. La regla de oro: "not your keys, not your coins".'},

  // ═══ FILOSOFÍA ═══
  {k:['filosofía','filósofo','sócrates','platón','aristóteles','nietzsche','kant','pensamiento','existencia','ética','moral','razón'], a:'La filosofía busca entender preguntas fundamentales sobre la existencia, conocimiento, verdad, moral y mente. Sócrates (470-399 a.C.) usó la mayéutica (diálogo para parir ideas). Platón fundó la Academia y la teoría de las Ideas. Aristóteles creó la lógica, la ética y la teoría del justo medio. Descartes: "Pienso, luego existo". Kant: el imperativo categórico (actúa de modo que tu acción sea ley universal). Nietzsche: la voluntad de poder, el superhombre, la crítica a la moral cristiana.'},
  {k:['sabio','sabiduría','reflexión','pensamiento','profundo','enseñanza','lección','cita','frase','proverbio'], a:'Reflexiones: "Solo sé que no sé nada" - Sócrates. "El conocimiento habla, pero la sabiduría escucha" - Jimi Hendrix. "Viaja, lee, ama, sueña, aprende. La vida es una y las experiencias son lo único que te llevarás". "No juzgues a alguien sin caminar una milla en sus zapatos". "El mayor riesgo es no tomar ningún riesgo". "Sé el cambio que quieres ver en el mundo" - Gandhi. "La felicidad no es tener lo que quieres, sino querer lo que tienes". "No es más rico quien más tiene, sino quien menos necesita".'},
  {k:['dios','religión','espiritual','fe','creencia','iglesia','cristiano','católico','budista','musulmán','hinduismo','judío','orar','reza','ateo','agnóstico'], a:'Principales religiones del mundo por seguidores: Cristianismo (2.400M), Islam (1.900M), Hinduismo (1.200M), Budismo (500M), Religiones tradicionales chinas (~400M), Judaísmo (14M). También hay personas sin religión (ateos, agnósticos, ~1.200M). Cada religión tiene sus creencias, textos sagrados y prácticas. El diálogo interreligioso promueve la paz y el respeto mutuo. La libertad de creencia es un derecho humano fundamental. Respetar las diferencias es clave para la convivencia.'},

  // ═══ ARTE Y CULTURA ═══
  {k:['arte','pintura','museo','galería','cuadro','escultura','obra','artista','pintor','exposición','mural'], a:'Obras maestras del arte: Mona Lisa (Leonardo da Vinci, Louvre), La noche estrellada (Van Gogh, MoMA), El Guernica (Picasso, Reina Sofía), La persistencia de la memoria (Dalí, MoMA), Las meninas (Velázquez, Prado), El grito (Munch, Oslo), La creación de Adán (Miguel Ángel, Capilla Sixtina). Movimientos: Renacimiento, Barroco, Impresionismo, Cubismo, Surrealismo, Expresionismo, Pop Art. Latinoamérica: Frida Kahlo, Diego Rivera, Fernando Botero, David Alfaro Siqueiros, José Clemente Orozco.'},
  {k:['música','canción','cantar','ritmo','melodía','artista','banda','concierto','instrumento','guitarra','piano','batería'], a:'Géneros musicales: Clásica (Beethoven, Mozart, Bach), Jazz (Miles Davis, Louis Armstrong), Rock (The Beatles, Queen, Led Zeppelin), Pop (Michael Jackson, Madonna, Taylor Swift), Electrónica (Daft Punk, Kraftwerk), Hip-Hop (Tupac, Kendrick Lamar), Reggaetón (Daddy Yankee, Bad Bunny), Salsa (Celia Cruz, Héctor Lavoe), Bachata (Juan Luis Guerra), Tango (Carlos Gardel), Flamenco (Camarón, Paco de Lucía). Beneficios de la música: reduce estrés, mejora el ánimo, estimula la memoria.'},
  {k:['película','cine','ver','recomendar','pelis','film','director','actor','peli','netflix', 'marvel','dc','star','wars'], a:'Películas recomendadas: "El Padrino" (gangster, 1972), "Interestelar" (ciencia ficción, 2014), "Parásitos" (drama coreano, 2019), "El viaje de Chihiro" (animación, 2001), "Forrest Gump" (drama, 1994), "El Señor de los Anillos" (fantasía épica, 2001-2003), "Matrix" (ciencia ficción, 1999), "Todo en todas partes al mismo tiempo" (acción/comedia, 2022), "Volver al futuro" (ciencia ficción, 1985), "La vida es bella" (drama, 1997). Directores: Nolan, Tarantino, Cuarón, Iñárritu, del Toro, Almodóvar.'},
  {k:['libro','recomendar','leer','lectura','novela','literatura','autor','biblioteca','escritor','best','seller'], a:'Libros recomendados: "Cien años de soledad" - Gabriel García Márquez (realismo mágico, Premio Nobel), "1984" - George Orwell (distopía), "El principito" - Saint-Exupéry (fábula filosófica), "Don Quijote de la Mancha" - Cervantes (clásico español), "La sombra del viento" - Carlos Ruiz Zafón, "Fahrenheit 451" - Ray Bradbury, "Sapiens" - Yuval Noah Harari (historia humana), "El Aleph" - Borges, "Rayuela" - Cortázar, "Pedro Páramo" - Juan Rulfo.'},
  {k:['poema','poesía','verso','rima','literatura','poeta','escribir','poético','neruda','benedetti','borges','paz'], a:'Poetas hispanoamericanos: Pablo Neruda (Chile, "20 poemas de amor"), Gabriela Mistral (Chile, Premio Nobel), Octavio Paz (México, Premio Nobel), Jorge Luis Borges (Argentina), Mario Benedetti (Uruguay), Alfonsina Storni (Argentina), Federico García Lorca (España), Antonio Machado (España), César Vallejo (Perú), José Martí (Cuba). Poema breve de Benedetti: "No te rindas, por favor no cedas, aunque el frío queme, aunque el miedo muerda, aunque el sol se esconda, y se calle el viento, aún hay fuego en tu alma, aún hay vida en tus sueños."'},
  {k:['museo','museo','museo','nacional','historia','antropología','arte','cultura','galería'], a:'Museos importantes: Museo del Louvre (París, Mona Lisa, Venus de Milo), Museo Nacional de Antropología (CDMX, Piedra del Sol), Museo del Prado (Madrid, Goya, Velázquez), Museo Reina Sofía (Madrid, Guernica), MoMA (Nueva York, arte moderno), Museo de Arte Contemporáneo (Buenos Aires), Museo Nacional de Colombia (Bogotá), Museo de la Nación (Lima), Museo Nacional de Bellas Artes (Santiago de Chile), MALBA (Buenos Aires, arte latinoamericano).'},
  {k:['navidad','año','nuevo','diciembre','fiesta','celebrar','25','diciembre','regalo','árbol','pascua','navideño','papá','noel','reyes','magos','santa'], a:'La Navidad se celebra el 25 de diciembre. Tradiciones por país: España: cena familiar (cordero, marisco), uvas en Nochevieja (12 campanadas), Reyes Magos (6 enero, regalos). México: posadas, piñatas, nacimiento, cena de pavo o bacalao. Argentina: cena al aire libre (verano), brindis con sidra, fuegos artificiales. Colombia: Novena de Aguinaldos, cena familiar, regalos. Venezuela: hallacas, pan de jamón, gaitas. En todo el mundo: árbol de Navidad, luces, intercambio de regalos.'},

  // ═══ DEPORTES ═══
  {k:['fútbol','mundial','liga','champions','liga','española','premier','serie','bundesliga','messi','ronaldo','neymar','mbappé','haaland'], a:'El fútbol es el deporte más popular del mundo. Las mejores ligas: Premier League (Inglaterra), LaLiga (España), Serie A (Italia), Bundesliga (Alemania), Ligue 1 (Francia), Brasileirão (Brasil), Liga MX (México). La Champions League es el torneo de clubes más prestigioso. La Copa Mundial se celebra cada 4 años (2026 en EEUU/México/Canadá). Los máximos goleadores históricos: Cristiano Ronaldo (~870 goles), Lionel Messi (~820). Pelé y Maradona son leyendas. Clubes con más Champions: Real Madrid (14), AC Milan (7), Liverpool (6).'},
  {k:['olimpiadas','juegos','olímpicos','JJOO','oro','plata','bronce','medalla','atleta','deporte','olimpismo'], a:'Los Juegos Olímpicos se celebran cada 4 años (alternando verano e invierno cada 2 años). París 2024 fue la última edición de verano. Los JJOO modernos comenzaron en 1896 (Atenas), inspirados en los antiguos Juegos Olímpicos griegos (776 a.C.). Los 5 aros representan los 5 continentes unidos por el deporte. Países con más medallas históricas: EE.UU., URSS, Reino Unido, China. Atletas destacados: Michael Phelps (natación, 28 medallas), Usain Bolt (100m, 200m), Simone Biles (gimnasia), Carl Lewis (atletismo).'},
  {k:['ejercicio','físico','gimnasio','entrenar','pesas','cardio','fuerza','flexibilidad','rutina','entrenamiento'], a:'Rutina completa cuerpo (3-4 veces/semana): 1) Sentadillas (piernas/glúteos) 3x15. 2) Flexiones (pecho/hombros) 3x al fallo. 3) Remo con mochila (espalda) 3x12. 4) Press de hombros con botellas 3x12. 5) Plancha (core) 3x30-60 seg. 6) Zancadas (piernas) 3x10 cada pierna. 7) Burpees (cardio) 3x10. Descansa 60 seg entre series. Calienta 5 min antes y estira 5 min después. Aumenta peso/reps progresivamente (progresión). La constancia es más importante que la intensidad.'},

  // ═══ EMOCIONES ═══
  {k:['amor','relación','pareja','novio','novia','enamorado','sentimiento','corazón','romance','cariño','querer'], a:'El amor es un sentimiento complejo. Relaciones saludables se basan en: comunicación honesta, confianza mutua, respeto, apoyo, espacio personal, metas compartidas. Señales de alerta: celos excesivos, control, falta de respeto, manipulación. El amor propio es el primer paso para amar a otros. Como dijo García Márquez: "No llores porque terminó, sonríe porque sucedió." No idealices el amor de película; el amor real requiere trabajo, paciencia y compromiso diario.'},
  {k:['amistad','amigo','lealtad','confianza','compañero','cuate','colega','camarada','hermano','mejor','amigo'], a:'La amistad verdadera se basa en: confianza (saber que el otro estará ahí), honestidad (decir la verdad incluso cuando es difícil), apoyo incondicional (celebrar logros y acompañar en derrotas), respeto por las diferencias, reciprocidad (dar y recibir), tiempo de calidad. No se trata de la cantidad de amigos sino de la calidad. Como Cicerón: "La amistad duplica las alegrías y divide las tristezas." Cultiva tus amistades: llama, escribe, queda, escucha.'},
  {k:['triste','llorar','pena','melancolía','desánimo','desmotivado','abatido','deprimido','bajo','ánimo','desaliento','tristeza'], a:'Es normal sentirse triste. La tristeza es una emoción humana válida. Para sobrellevarla: 1) Permítete sentir sin juzgarte. 2) Habla con alguien de confianza. 3) Escribe lo que sientes (diario). 4) Haz ejercicio (aunque sea caminar 15 min). 5) Escucha música que te haga bien. 6) Haz algo que solía gustarte. 7) Sal a la luz del día. 8) Si persiste por semanas, considera ayuda profesional. No estás solo, todos pasamos por momentos difíciles. "Esto también pasará."'},
  {k:['miedo','temor','asustado','preocupación','ansiedad','valiente','valor','enfrentar','superar','miedo','fobia'], a:'El miedo es una emoción natural que nos protege. Para manejarlo: 1) Identifica qué temes exactamente. 2) Evalúa si el miedo es racional (peligro real) o irracional (imaginado, exagerado). 3) Respira profundo cuando sientas miedo (inhala 4s, sostén 4s, exhala 6s). 4) Enfréntalo gradualmente (exposición progresiva). 5) Habla con alguien. 6) La valentía no es no tener miedo, es actuar a pesar del miedo. "El coraje no es la ausencia de miedo, sino la capacidad de seguir adelante a pesar del miedo."'},
  {k:['soledad','solo','solitario','compañía','socializar','conectar','grupo','persona','amigo','nuevo'], a:'Para conectar con otros: 1) Únete a grupos de tus intereses (deportes, lectura, música, arte). 2) Haz voluntariado (ayudar a otros también te conecta). 3) Toma clases o talleres (cocina, idiomas, baile). 4) Habla con desconocidos en contextos seguros (cafetería, librería). 5) Usa apps de amistad o eventos (Meetup). 6) Inicia conversaciones simples ("Qué libro interesante", "Recomiendas algún café por aquí?"). 7) La calidad de las conexiones importa más que la cantidad.'},
  {k:['felicidad','feliz','alegría','contento','bienestar','plenitud','satisfacción','disfrutar','sonrisa','agradecer'], a:'Estudios científicos muestran que la felicidad se construye con: 1) Conexiones sociales significativas (lo más importante). 2) Gratitud (agradecer lo que tienes). 3) Ayudar a otros (genera satisfacción). 4) Estar presente (mindfulness). 5) Metas y propósito de vida. 6) Ejercicio regular y sueño adecuado. 7) Experiencias sobre posesiones. La felicidad no es un destino sino un camino. No se trata de tener todo lo que quieres, sino de querer todo lo que tienes.'},
  {k:['éxito','triunfo','lograr','meta','objetivo','superación','motivación','esfuerzo','disciplina','éxito'], a:'El éxito es la suma de pequeños esfuerzos repetidos día tras día. Claves: 1) Define metas claras y específicas (SMART). 2) Divide en pasos pequeños. 3) Celebra logros intermedios. 4) Aprende de los fracasos. 5) Rodéate de personas que te apoyen. 6) La disciplina es más importante que la motivación. 7) "La suerte es donde se encuentran la preparación y la oportunidad" - Séneca. 8) Compara tu progreso con tu yo de ayer, no con otros. El camino es tan importante como la meta.'},
  {k:['fracaso','error','fallar','fallo','equivocar','intentar','otra','vez','perseverancia','fracaso','equivocación', 'caída'], a:'El fracaso no es el final, es parte del camino. Thomas Edison: "No fracasé, solo encontré 10.000 formas que no funcionaban" (antes de crear la bombilla). J.K. Rowling fue rechazada por 12 editoriales antes de Harry Potter. Michael Jordan fue cortado de su equipo escolar de baloncesto. Steve Jobs fue despedido de Apple, la empresa que fundó. La clave no es evitar caer, sino levantarse cada vez. Cada error es una lección. "Falla rápido, falla seguido, falla hacia adelante" es el lema del emprendimiento.'},

  // ═══ IDIOMAS ═══
  {k:['idioma','español','castellano','lengua','hablar','gramática','palabra','vocabulario','acento','ortografía','rae'], a:'El español (o castellano) es la segunda lengua más hablada del mundo por nativos (~500M). Idioma oficial en 21 países. Origen: latín vulgar + influencia del árabe (8 siglos, ~4.000 palabras de origen árabe como aceite, almohada, guitarra, ojalá). La RAE (Real Academia Española) regula su uso. Características: la Ñ es única del español, es una lengua romance (como francés, italiano, portugués), tiene 27 letras. Dato curioso: el español es más rápido de hablar que el inglés pero más lento que el japonés (sílabas por segundo).'},
  {k:['aprender','idioma','inglés','clases','estudiar','práctica','hablar','escribir','leer','escuchar','nivel','básico','intermedio','avanzado'], a:'Método para aprender inglés por tu cuenta: 1) Inmersión: cambia tu teléfono a inglés. 2) Input comprensible: mira series en inglés con subtítulos en inglés (recomendadas: Friends, The Office, Breaking Bad). 3) Escucha podcasts: 6 Minute English (BBC), The English We Speak. 4) Lee noticias: BBC News, The Guardian en nivel fácil. 5) Apps: Duolingo (básico), Anki (vocabulario con repetición espaciada), HelloTalk (hablar con nativos). 6) Piensa en inglés (narración interna). 7) Errores son parte del proceso. 8) Invertir 30 min diarios es mejor que 3h una vez a la semana.'},

  // ═══ ANIMALES Y NATURALEZA ═══
  {k:['animal','mascota','perro','gato','pájaro','pez','conejo','cuidar','veterinario','raza','adoptar'], a:'Tener una mascota es una responsabilidad. Perros: necesitan paseos diarios (30-60 min), alimentación balanceada, agua fresca, vacunas, desparasitación, cariño, adiestramiento básico. Gatos: más independientes pero necesitan arena limpia, alimentación de calidad, agua, rascadores, enriquecimiento ambiental, cariño. Antes de adoptar considera: espacio, tiempo, presupuesto (comida, veterinario, imprevistos). Adoptar es mejor que comprar (miles de animales esperan hogar en refugios). Esteriliza a tus mascotas.'},
  {k:['perros','razas','perro','pastor','alemán','labrador','golden','retriever','bulldog','poodle','chihuahua','husky','dálmata','rottweiler','doberman'], a:'Razas de perros populares: 1) Labrador Retriever: amigable, activo, excelente con niños. 2) Pastor Alemán: inteligente, leal, protector (ideal para trabajo policial). 3) Golden Retriever: cariñoso, paciente, buen perro de familia. 4) Bulldog: tranquilo, robusto, ronca. 5) Poodle: inteligente, hipoalergénico, viene en 3 tamaños. 6) Chihuahua: pequeño, valiente, apegado a su dueño. 7) Husky: enérgico, independiente, vocal. 8) Rottweiler: fuerte, leal, protector (necesita socialización temprana).'},
  {k:['gatos','razas','gato','felino','persa','siamés','bengalí','maine','coon','sphynx','angora','común','europeo'], a:'Razas de gatos: 1) Común Europeo: el más popular, adaptable, saludable. 2) Persa: pelaje largo, cara chata, tranquilo. 3) Siamés: elegante, vocal, muy apegado. 4) Bengalí: aspecto salvaje (manchas como leopardo), activo, curioso. 5) Maine Coon: gigante (hasta 10kg), amigable, pelaje denso. 6) Sphynx: sin pelo, cariñoso, necesita baños frecuentes. 7) Angora: pelaje largo y sedoso, inteligente. Los gatos domésticos pasan ~70% de su vida durmiendo. Se comunican con maullidos (solo para humanos), ronroneo, bufidos, lenguaje corporal.'},

  // ═══ VARIOS ═══
  {k:['broma','chiste','reír','risa','chistos','gracioso','divertido','humor','cuenta','chiste','cómico'], a:'¿Por qué los programadores confunden Halloween con Navidad? Porque OCT 31 = DEC 25. (¡Explicación: OCT es octal, 31 octal = 25 decimal, y DEC es decimal! Vale, es un chiste de informáticos.) ¿Qué le dice un pez a otro pez? "¿Llevas encurvado?" (nada, eso es un anzuelo). ¿Sabes cuál es el colmo de un callejón? Tener salida de emergencia. ¿Y de un batería? Tener hijos mellizos. ¿Cuál es el animal más antiguo? La cebra, porque está en blanco y negro. ¿Quieres otro chiste? ¡Pídemelo!'},
  {k:['consejo','recomendación','sugerencia','ayuda','consejos','útil','tip','truco','recomienda','aconseja'], a:'Consejo del día: La técnica Pomodoro para productividad: 1) Elige una tarea. 2) Pon un temporizador de 25 minutos. 3) Trabaja en la tarea sin interrupciones. 4) Cuando suene, toma un descanso de 5 minutos. 5) Después de 4 pomodoros, toma un descanso largo de 15-30 minutos. Beneficios: mejora el enfoque, reduce la procrastinación, evita el agotamiento, y hace que las tareas grandes parezcan más manejables. Aplica también para estudiar y para tareas domésticas.'},
  {k:['emergencia','peligro','ayuda','urgente','911','112','ambulancia','bombero','policía','hospital','emergencia','número'], a:'Números de emergencia: España: 112. México: 911. Argentina: 911. Colombia: 123. Chile: 133 (Carabineros), 131 (Ambulancia), 132 (Bomberos). Perú: 105 (Policía), 117 (Ambulancia), 116 (Bomberos). Venezuela: 911. EE.UU. y Canadá: 911. Recomendaciones: memoriza el número de tu país, mantén la calma al llamar, proporciona ubicación exacta, describe claramente la emergencia. Para emergencias médicas: no muevas a la persona lesionada, aplica primeros auxilios básicos si sabes, espera a los profesionales.'},
  {k:['viaje','viajar','turismo','vacaciones','vuelo','hotel','destino','mochilero','aventura','pasaporte','visa'], a:'Planificación de viaje: 1) Define presupuesto y fechas. 2) Investiga destino (clima, cultura, moneda, idioma, seguridad, requisitos de visa). 3) Reserva vuelo y alojamiento con anticipación (Skyscanner, Booking, Airbnb). 4) Seguro de viaje (imprescindible, cubre emergencias médicas). 5) Maleta: ropa según clima, zapatos cómodos, adaptador de corriente, botiquín básico. 6) Apps útiles: Maps.me (mapas offline), Google Translate, XE Currency, WhatsApp. 7) Respeta la cultura local. 8) Lleva copias de documentos importantes.'},
  {k:['política','gobierno','presidente','democracia','voto','elección','partido','constitución','político','ciudadano'], a:'La política organiza el poder en la sociedad. La democracia (del griego "poder del pueblo") se basa en la soberanía popular mediante el voto. Los 3 poderes del Estado (Montesquieu): Ejecutivo (gobierno, administra), Legislativo (congreso, hace leyes), Judicial (tribunales, juzga). La participación ciudadana (votar, informarse, opinar, protestar pacíficamente) es fundamental. Los partidos políticos representan diferentes ideologías. Es importante votar informado y exigir transparencia a los gobernantes.'},
  {k:['medio','ambiente','ecología','reciclar','reciclaje','plástico','basura','residuo','contaminación','sostenible','verde','naturaleza'], a:'Acciones para reducir tu huella ecológica: 1) Las 3R: Reduce, Reutiliza, Recicla. 2) Evita plásticos de un solo uso (botellas, bolsas, pajitas). 3) Usa bolsa reutilizable. 4) Separa residuos (orgánico, inorgánico, vidrio, papel/cartón, plástico/metal). 5) Ahorra agua (duchas cortas, cierra el grifo). 6) Ahorra electricidad (LED, apaga lo que no uses). 7) Transporte sostenible (caminar, bici, transporte público). 8) Consume productos locales y de temporada. 9) Composta residuos orgánicos. 10) Planta árboles.'},
  {k:['vegano','veganismo','vegetarianismo','vegetal','vegana','vegetariano','vegetal','planta','proteína','tofu','seitán','tempeh'], a:'Dieta vegana/vegetariana: excluye productos animales. Beneficios: menor impacto ambiental, reduce sufrimiento animal, puede mejorar salud cardiovascular. Precauciones nutricionales: 1) Vitamina B12: suplemento obligatorio (no existe en plantas). 2) Hierro: lentejas, espinacas, legumbres (mejor absorción con vitamina C, ej. limón). 3) Calcio: brócoli, col rizada, almendras, bebidas vegetales fortificadas. 4) Proteína completa: combina legumbres + cereales (lentejas+arroz, garbanzos+pan). 5) Omega-3: semillas de chía y lino, nueces. 6) Vitamina D: sol o suplemento.'},

  // ═══ MATEMÁTICAS ═══
  {k:['número','pi','matemáticas','constante','3.1416','círculo','geometría','calcul','álgebra','trigonometría'], a:'π (Pi) = 3.14159265358979... Es la relación entre la circunferencia de un círculo y su diámetro. Es un número irracional (decimales infinitos que no se repiten) y trascendental. Se ha calculado con billones de decimales pero solo 39 son suficientes para cálculos científicos precisos (para calcular la circunferencia del universo observable con margen de error del tamaño de un átomo). Se celebra el Día de Pi el 14 de marzo (3/14). También es el cumpleaños de Einstein.'},
  {k:['matemáticas','suma','resta','multiplicación','división','calcular','número','problema','calculadora','ejercicio'], a:'Puedo ayudarte con cálculos básicos (suma, resta, multiplicación, división, potencias, raíces cuadradas). Escríbeme la operación y te daré el resultado. Por ejemplo: "cuánto es 15 * 7", "calcula 2^10", "raíz cuadrada de 144". Para problemas más avanzados, puedo explicarte los conceptos y métodos paso a paso. ¿Qué necesitas calcular?'},

  // ═══ CONTEXTO (frases para cuando no hay match) ═══
  {k:['no','entiendo','comprender','explica','mejor','otra','vez','repita','claramente','no entendí'], a:'Claro, déjame explicarlo de otra manera. ¿Puedes ser más específico con tu pregunta o decirme con qué necesitas ayuda exactamente? Puedo hablarte de ciencia, tecnología, historia, geografía, salud, cocina, finanzas, y muchos otros temas.'},
  {k:['más','dime','más','continua','sigue','cuéntame','cuenta','más','amplía','profundiza','detalle'], a:'¿Sobre qué tema te gustaría saber más? Puedo profundizar en ciencia, historia, geografía, tecnología, salud, filosofía, cocina, y muchos otros temas. Solo dime cuál te interesa y te daré más información.'},
  {k:['otro','cambio','tema','diferente','vario','vamos','variar','cambiar'], a:'Claro, ¿sobre qué otro tema te gustaría hablar? Tengo información sobre ciencia, historia, geografía, tecnología, salud, cocina, finanzas, arte, deportes, emociones, y muchos más. ¡Elige el que más te interese!'},
  {k:['hola','x0gpt','asistente','ayuda','presenta','inicio','empezar','comenzar','arrancar'], a:'¡Hola! Soy X0GPT, tu asistente IA. Estoy aquí para ayudarte. Puedes preguntarme sobre ciencia, historia, geografía, tecnología, salud, cocina, finanzas, filosofía, arte, deportes, y mucho más. Todo funciona 100% offline y privado en tu navegador. ¿Qué te gustaría saber?'},
];
